apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kubernetes-minikube
  namespace: argocd
spec:
  project: default
  source: 
   repoURL: "https://github.com/Raihan11x/Kubernetes-Minikube"
   targetRevision: HEAD
   path: complete-devops-project-time-printer
  destination: 
   server: "https://kubernetes.default.svc"
   namespace: default
  syncPolicy:
   automated:
    prune: true
    selfHeal: true